from app.rag_context import build_rag_context
from app.llm_client import ask_llm
from app.safety_filter import scan_answer, format_safety_warning


INSTALLER_FILE_KEYWORDS = [
    "autoinstall",
    "user-data",
    "preseed",
    "kickstart",
    "autoyast",
    "archinstall config",
    "bootable iso",
    "usb image",
    "installer file",
    "installation file",
    "wipe my disk",
    "wiping my disk",
    "unattended install",
    "automatic install",
]


def is_installer_file_request(question: str) -> bool:
    q = question.lower()
    return any(keyword in q for keyword in INSTALLER_FILE_KEYWORDS)


def installer_file_policy_response() -> str:
    return (
        "I can't generate a full OS installer file, disk-wiping autoinstall file, "
        "preseed, kickstart, AutoYaST file, Archinstall config, bootable ISO, or USB image workflow directly in normal chat.\n\n"
        "Use the gated script instead:\n\n"
        "1. Collect the frontend profile:\n"
        "`python scripts/collect_system_profile.py --no-db --frontend-json > /tmp/linuxai_frontend_profile.json`\n\n"
        "2. Generate draft installer files:\n"
        "`python scripts/generate_install_files.py --profile /tmp/linuxai_frontend_profile.json --installer ubuntu-autoinstall --allow-installer-files --confirm I_UNDERSTAND_INSTALLER_FILES_ARE_DANGEROUS --overwrite`\n\n"
        "This creates draft files in `generated/installers/<profile_id>/ubuntu-autoinstall/`. "
        "It does not write to USB, does not create a bootable ISO, and does not modify disks."
    )


def answer_question(question: str) -> str:
    if is_installer_file_request(question):
        return installer_file_policy_response()

    context = build_rag_context(question)

    prompt = f"""
You are LinuxAI, a careful Linux hardware troubleshooting assistant.

Answer in English.
Use the retrieved SQL facts and vector documents as the main source of truth.
Keep the answer concise, practical, and safe.

INSTALLER FILE GENERATION POLICY:
- The normal assistant must not generate full OS installer files, bootable ISO files, USB image writing workflows, Ubuntu autoinstall user-data, Debian preseed, Fedora kickstart, Archinstall config, AutoYaST XML, partitioning files, or disk-writing commands directly in chat.
- The normal assistant may provide explanations, safe install plans, diagnostic commands, package installation commands, and post-install checklists.
- If the user asks to generate full installer files, do not use the normal troubleshooting 5-section format.
- If the user asks to generate full installer files, refuse to output the file contents and explain that installer files can only be generated through the gated script: scripts/generate_install_files.py.
- Tell the user to first collect a frontend profile with:
  python scripts/collect_system_profile.py --no-db --frontend-json > /tmp/linuxai_frontend_profile.json
- Then tell the user to run:
  python scripts/generate_install_files.py --profile /tmp/linuxai_frontend_profile.json --installer ubuntu-autoinstall --allow-installer-files --confirm I_UNDERSTAND_INSTALLER_FILES_ARE_DANGEROUS --overwrite
- Do not output complete installer file contents in normal chat.
- Do not output destructive disk commands such as dd, mkfs, wipefs, parted, fdisk, sfdisk, cryptsetup, or grub-install.
- Installer draft files may only be generated by scripts/generate_install_files.py with explicit confirmation.

USER QUESTION:
{question}

RETRIEVED CONTEXT:
{context}

IMPORTANT RULES:
- Use this workflow for every issue: diagnose first, then decide, then act, then verify.
- Do not jump directly to installation, removal, purge, module reload, blacklisting, Secure Boot changes, driver switching, or bootloader changes.
- Action commands are allowed only when diagnostics or retrieved context clearly support them.
- If diagnostics are missing, Next steps must not contain action commands.
- If diagnostics are missing, write: No action command recommended until diagnostics are reviewed.
- Rollback must not be more dangerous than the suggested action.
- Never use purge/remove as a generic rollback.
- Never suggest exact package versions unless they appear in the retrieved context.
- Prefer reversible checks over system-changing commands.
- Maximum 2 commands per section.
- Every command must be a valid Linux shell command.
- Never use markdown code fences.
- Never use triple backticks.
- Never wrap Risk, Command, or Explanation in a code block.
- Do not suggest blacklisting nouveau unless diagnostics show nouveau is loaded or conflicting.
- Do not suggest removing or purging firmware packages.
- Never suggest purging linux-firmware.
- Do not recommend disabling Secure Boot as the first solution.
- Do not claim DKMS bypasses Secure Boot.
- If no safe rollback exists, say: No safe rollback command is recommended at this stage.
- Do not place action commands in Check first.

TOPIC-SPECIFIC RULES:
- For NVIDIA issues, treat nvidia-smi as a low-risk verification command.
- For NVIDIA laptop GPUs, prefer lspci -nnk | grep -A4 -E "VGA|3D|Display".
- For "nvidia-smi no devices were found", check lspci, lsmod, and mokutil before suggesting changes.
- For Wi-Fi issues, check lspci -nnk, rfkill list, lsmod, and dmesg firmware messages before suggesting module reloads.
- For Bluetooth issues, check rfkill list, systemctl status bluetooth, bluetoothctl list, and dmesg Bluetooth messages before suggesting module reloads.
- For Intel audio issues, prefer cat /proc/asound/cards, systemctl --user status pipewire, pactl list short sinks, and dmesg | grep -i -E "sof|audio|snd".
- For overheating or battery drain, first check temperatures, active GPU, power profile, and NVIDIA process usage.

COMMAND FORMAT:
Every command must use exactly this markdown-bold structure:

**Risk: low**
**Command:** `command_here`
**Explanation:** one short sentence.

Rules for command formatting:
- Do not put the risk label inside the command.
- Do not put comments inside the command.
- Do not put two unrelated commands in one Command line.
- The command inside backticks must contain only the shell command.
- Do not use triple backticks.
- Do not use fenced code blocks.

SPECIAL CASE:
If the user asks to create, generate, write, output, or provide a complete installer file, autoinstall file, preseed file, kickstart file, AutoYaST file, Archinstall config, bootable ISO, USB image workflow, disk wiping workflow, or unattended installation file, do not use the 5-section troubleshooting format. Instead, briefly say that normal chat cannot generate full installer files and point them to the gated script workflow.

ANSWER FORMAT:
Use exactly these 5 sections:

### 1. Summary
Briefly explain what is assumed based on the user question and retrieved context.

### 2. Check first
Diagnostic commands only.
Maximum 2 commands.
Use the exact command format.

### 3. Next steps
Action commands only if diagnostics confirm the issue.
Maximum 2 commands.
Use the exact command format.

### 4. Verify result
Verification commands or checks.
Maximum 2 commands.
Use the exact command format.

### 5. Risks and rollback
Mention risks clearly.
Give rollback only if it is safe and relevant.
If rollback is risky or unclear, say that no safe rollback command is recommended at this stage.
"""

    answer = ask_llm(prompt)
    issues = scan_answer(answer)

    if issues:
        answer += format_safety_warning(issues)

    return answer